[project]
name = "comp5318"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Prajwal Bankar", email = "prajwal.bankar.18@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
]

[project.scripts]
comp5318 = "comp5318:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
